// crate/build.rs
//
// Auto-discovers every *.json file under ../sources/verified/,
// ../sources/community/, and ../sources/private/, and generates a Rust
// file that `include_str!`s each one into a static array. This is what
// makes adding a new source a pure data change: drop a JSON file in
// sources/community/ (or sources/private/ for an authenticated site),
// and the NEXT BUILD picks it up automatically — nobody edits Rust
// code, nobody edits a manifest, nobody touches registry.rs.
//
// sources/private/ vs the other two: same merge/id-uniqueness rules as
// verified/community (see registry.rs's build_from_files), the only
// difference is WHAT the sites in it are — every source in private/
// requires request.auth (a per-user cookie) to search at all. Kept
// physically separate from verified/community purely so a contributor
// scanning the sources/ tree can immediately see which sites need a
// login and which don't, without opening every file.
//
// ../sources/special-sites.json is embedded the same way for the
// special_sites block (kdrama/nyaa/tokyotosho-style bespoke sites).
//
// Re-runs automatically whenever a file under sources/ changes, thanks
// to the cargo:rerun-if-changed directives below.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let sources_dir = manifest_dir.join("..").join("sources");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_file = out_dir.join("embedded_sources.rs");

    let verified_dir = sources_dir.join("verified");
    let community_dir = sources_dir.join("community");
    let private_dir = sources_dir.join("private");
    let special_file = sources_dir.join("special-sites.json");

    println!("cargo:rerun-if-changed={}", verified_dir.display());
    println!("cargo:rerun-if-changed={}", community_dir.display());
    println!("cargo:rerun-if-changed={}", private_dir.display());
    println!("cargo:rerun-if-changed={}", special_file.display());

    let verified_entries = discover_json_files(&verified_dir);
    let community_entries = discover_json_files(&community_dir);
    let private_entries = discover_json_files(&private_dir);

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by build.rs — do not edit by hand.\n\n");

    emit_array(&mut out, "EMBEDDED_VERIFIED", &verified_entries, &manifest_dir);
    emit_array(&mut out, "EMBEDDED_COMMUNITY", &community_entries, &manifest_dir);
    emit_array(&mut out, "EMBEDDED_PRIVATE", &private_entries, &manifest_dir);

    if special_file.exists() {
        let rel = pathdiff(&special_file, &manifest_dir);
        out.push_str(&format!(
            "pub static EMBEDDED_SPECIAL_SITES: &str = include_str!(\"{}\");\n",
            rel
        ));
    } else {
        out.push_str("pub static EMBEDDED_SPECIAL_SITES: &str = \"{}\";\n");
    }

    fs::write(&out_file, out).expect("failed to write embedded_sources.rs");
}

fn discover_json_files(dir: &Path) -> Vec<PathBuf> {
    if !dir.exists() {
        return Vec::new();
    }
    let mut files: Vec<PathBuf> = fs::read_dir(dir)
        .expect("failed to read sources directory")
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|p| p.extension().map(|e| e == "json").unwrap_or(false))
        .collect();
    files.sort(); // deterministic build output
    files
}

fn emit_array(out: &mut String, const_name: &str, files: &[PathBuf], manifest_dir: &Path) {
    out.push_str(&format!(
        "pub static {const_name}: &[(&str, &str)] = &[\n"
    ));
    for file in files {
        let filename = file.file_name().unwrap().to_string_lossy();
        let rel = pathdiff(file, manifest_dir);
        out.push_str(&format!(
            "    (\"{filename}\", include_str!(\"{rel}\")),\n"
        ));
    }
    out.push_str("];\n\n");
}

/// Relative path from `base` to `target`, for use inside include_str!()
/// (which resolves relative to the file containing the macro call — the
/// generated file lives in OUT_DIR, so we instead emit paths relative
/// to CARGO_MANIFEST_DIR and rely on include_str! accepting an absolute
/// path built from env!("CARGO_MANIFEST_DIR") at the call site... in
/// practice simplest is to just emit an absolute path directly.
fn pathdiff(target: &Path, _base: &Path) -> String {
    let canonical = fs::canonicalize(target)
        .unwrap_or_else(|_| target.to_path_buf());
    canonical.to_string_lossy().replace('\\', "\\\\")
}
